FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY webrtc-signaling/go.mod ./
COPY webrtc-signaling/main.go ./
RUN CGO_ENABLED=0 GOFLAGS="-insecure" go build -mod=mod -o /signaling-server .

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /signaling-server .

EXPOSE 3004

CMD ["./signaling-server"]